#!/usr/bin/env bash

set -e

echo -e "\033[31;1;4mthis WILL override your current configuration.\033[0m"

echo "waiting 5 seconds before continuing"

sleep 5

for file in ~/.config/nixos/*; do
    file=$(basename "$file")

    echo -e "moving \033[94m/etc/nixos/$file\033[0m \033[32m->\033[0m \033[94m/etc/nixos/$file\033[4m.bak\033[0m"
    [ -f "/etc/nixos/$file" ] && sudo mv "/etc/nixos/$file" "/etc/nixos/$file.bak"

    echo -e "hardlinking \033[94m$HOME/.config/nixos/$file\033[0m \033[32m->\033[0m \033[94m/etc/nixos/$file\033[0m"
    sudo ln "$HOME/.config/nixos/$file" "/etc/nixos/$file"
done
