[language-server.rust-analyzer.config.check]
command = "clippy"

[[language]]
name = "html"
formatter = { command = "mylang-formatter" , args = ["--parser", "html"] }

[[language]]
name = "rust"

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
"'" = "'"
'`' = '`'
'<' = '>'
